version: '3.8'

services:
#  web:
#    build: .
#    command: uvicorn app.main:app --host 0.0.0.0 --port 80
#    volumes:
#      - .:/usr/src/personalised_nudges
#    ports:
#      - 80:80
#    depends_on:
#      - db

  db_alchemy:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web
    expose:
      - "5432:5432"

volumes:
  postgres_data: